---
title: "dataprep"
author: "Jack"
date: "2023-02-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
canopydifftri <- read_excel("~/Documents/R/hons_local_r/canopydifftri.xlsx", 
                            col_types = c("text", "numeric", "numeric"))
```
```{r}
View(canopydifftri2)
```

```{r}
summarise(canopydifftri2, Mean.TRI = mean(TRI))
```
```{r}
summarise(canopydifftri2,
  mean.activity = mean(TRI), # mean
  min.Activity = min(TRI), # minimum
  max.Activity = max(TRI), # maximum
  med.Activity = median(TRI), # median
  sd.Activity = sd(TRI), # standard deviation
  var.Activity = var(TRI), # variance
) # interquartile range
```
```{r}
#remove na values
summarise(canopydifftri2, mean.TRI = mean(TRI, na.rm = TRUE))
```
```{r}
summarise(canopydifftri2, mean.canopydiff = mean(canopydiff, na.rm = TRUE))
```

#sample size with na removed 
```{r}
length(canopydifftri2$TRI[!is.na(canopydifftri2$TRI)])
```
#396430 now, so 3570 na values in TRI data

```{r}
length(canopydifftri2$canopydiff[!is.na(canopydifftri2$canopydiff)])
```

#392584 now , so 7416 na values in canopy difference



```{r}
 is.na(canopydifftri2)
```





```{r}
summarise(canopydifftri2,
  mean.TRI = mean(TRI), # mean
  min.TRI = min(TRI), # minimum
  max.TRI = max(TRI), # maximum
  med.TRI = median(TRI), # median
  sd.TRI = sd(TRI), # standard deviation
  var.TRI = var(TRI), # variance
  n.TRI = n(), # sample size
  se.TRI = sd.TRI / sqrt(n.TRI), # standard error
  IQR.TRI = IQR(TRI)
) # interquartile range
```

