# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2023-04-11 14:23:11
"""
import arcpy
from arcpy.sa import *

def Model1():  # Model1

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    c26000_lasd5 = arcpy.Raster("c26000_lasd5")
    c26000_lasd5_2_ = arcpy.Raster("c26000_lasd5")
    c26000_lasd5_3_ = arcpy.Raster("c26000_lasd5")

    # Process: Focal Statistics (Focal Statistics) (sa)
    output_mean = "C:\\Users\\Jack\\Documents\\arc_file_24,3\\honours\\MyProject\\output_mean"
    Focal_Statistics = output_mean
    output_mean = arcpy.sa.FocalStatistics(in_raster=c26000_lasd5, neighborhood="Rectangle 3 3 CELL", statistics_type="MEAN", ignore_nodata="DATA", percentile_value=90)
    output_mean.save(Focal_Statistics)


    # Process: Focal Statistics (2) (Focal Statistics) (sa)
    min_1m = "C:\\Users\\Jack\\Documents\\arc_file_24,3\\honours\\MyProject\\min_1m"
    Focal_Statistics_2_ = min_1m
    min_1m = arcpy.sa.FocalStatistics(in_raster=c26000_lasd5_2_, neighborhood="Rectangle 3 3 CELL", statistics_type="MINIMUM", ignore_nodata="DATA", percentile_value=90)
    min_1m.save(Focal_Statistics_2_)


    # Process: Focal Statistics (3) (Focal Statistics) (sa)
    max_1m = "C:\\Users\\Jack\\Documents\\arc_file_24,3\\honours\\MyProject\\max_1m"
    Focal_Statistics_3_ = max_1m
    max_1m = arcpy.sa.FocalStatistics(in_raster=c26000_lasd5_3_, neighborhood="Rectangle 3 3 CELL", statistics_type="MAXIMUM", ignore_nodata="DATA", percentile_value=90)
    max_1m.save(Focal_Statistics_3_)


    # Process: Raster Calculator (Raster Calculator) (sa)
    tri_1m_katmb = "C:\\Users\\Jack\\Documents\\arc_file_24,3\\honours\\MyProject\\tri_1m_katmb"
    Raster_Calculator = tri_1m_katmb
    tri_1m_katmb = ( output_mean  -  min_1m)  / ( max_1m  - min_1m )
    tri_1m_katmb.save(Raster_Calculator)


if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"C:\Users\Jack\Documents\ArcGIS\Projects\hons_catalog_test\hons_catalog_test.gdb", workspace=r"C:\Users\Jack\Documents\ArcGIS\Projects\hons_catalog_test\hons_catalog_test.gdb"):
        Model1()
