---
title: "R Notebook"
output: html_notebook
---
```{r}
library(raster)
```

```{r}
r = raster("Map2.tif")
```

```{r}
library(tmap)
tm_shape(r) + tm_raster(style= "sd", n = 10 , palette = "Greys")
```
```{r}
elevatcourse <- aggregate(r, fact=100, fun=mean, expand=TRUE)
tm_shape(elevatcourse) + tm_raster(style= "cont") + tm_legend(outside = TRUE)
```
```{r}
elevatcourse <- disaggregate(r, fact=2)
tm_shape(elevatcourse) + tm_raster(style= "cont") + tm_legend(outside = TRUE)
```

```{r}
proj4string(r)
proj4string(r) <- CRS("+proj=utm +zone=19 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs")
```
```{r}
slope <- terrain(r, opt="slope", unit="radians", neighbors=8)
tm_shape(slope) + tm_raster() + tm_legend(outside = TRUE)
```


```{r}
proj4string(r)
slope <- terrain(r, opt="slope", unit="radians", neighbors=8)
tm_shape(slope) + tm_raster() + tm_legend(outside = TRUE)

aspect <- terrain(r, opt="aspect", unit="radians", neighbors=8)
tm_shape(aspect) + tm_raster() + tm_legend(outside = TRUE)
```
```{r}
shade <- hillShade(slope, aspect)
tm_shape(shade) +tm_raster(style="cont", palette = "Greys") +tm_legend(show=FALSE)
```
```{r}
library(spatialEco)
vrm(r, s = 3, file.name = NULL,)

```

```{r}
library(spatialEco)
tri(r, s =c(3,5), exact = TRUE, file.name = NULL,)
```

```{r}
library(geodiv)
sa(r) # average surface roughness
svk(r) # reduced valley depth
ssc(r) # mean summit curvature
```
```{r}
#root mean square roughness of a surface 
sq(r)
```

